GET http://localhost:3000/health
Content-Type: application/json

###

###  Criar pedido
POST http://localhost:3000/orders
Content-Type: application/json

{
  "customerId": "cust-123",
  "items": [
    { "productId": "p01", "quantity": 2 },
    { "productId": "p02", "quantity": 1 }
  ],
  "total": 150.5
}

###

###  Buscar pedido pelo ID
# Substitua {{id}} pelo id retornado na criação
GET http://localhost:3000/orders/89385bed-485e-4443-aeb3-08b2573a0577
Content-Type: application/json

###

###  Atualizar status do pedido (gera evento RabbitMQ)
PATCH http://localhost:3000/orders/89385bed-485e-4443-aeb3-08b2573a0577/status
Content-Type: application/json

{
  "status": "shipped"
}
###   "status": "enviado"
### PATCH /orders/{id}/status?status=enviado

###  Deletar pedido
DELETE http://localhost:3000/orders/{{id}}
Content-Type: application/json
